# -*- coding: utf-8 -*-
"""downsample_agedb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHgjQnDLUMnMa9a1jhyHjfHPSYCBW5aM
"""

import os
import shutil
import random
from collections import defaultdict
from tqdm import tqdm
from google.colab import drive

# --- Configuration ---
# Update this path to where your AgeDB folder is located in your Drive
source_dir = '/content/drive/MyDrive/UNIS6/cv/AgeDB'
base_output_dir = '/content/drive/MyDrive/UNIS6/cv/Downsamples'
target_subjects_count = 50
images_per_subject = 1

# 2. Group files by Subject Name
subject_map = defaultdict(list)
print("Reading file list from Drive (this may take a minute)...")
all_files = [f for f in os.listdir(source_dir) if f.endswith(('.jpeg', '.jpg'))]

for filename in all_files:
    parts = filename.split('_')
    if len(parts) >= 2:
        subject_name = parts[1]
        subject_map[subject_name].append(filename)

# 3. Filter subjects who have enough images
eligible_subjects = [name for name, files in subject_map.items() if len(files) >= images_per_subject]

if len(eligible_subjects) < target_subjects_count:
    print(f"Warning: Only found {len(eligible_subjects)} subjects with {images_per_subject}+ images.")
    selected_subjects = eligible_subjects
else:
    selected_subjects = random.sample(eligible_subjects, target_subjects_count)

# 4. Create folders and copy files to Local Runtime
print(f"Copying {len(selected_subjects) * images_per_subject} images to local storage...")
if os.path.exists(base_output_dir):
    shutil.rmtree(base_output_dir)

for subject in tqdm(selected_subjects):
    subject_folder = os.path.join(base_output_dir, subject)
    os.makedirs(subject_folder, exist_ok=True)

    # Pick random images for this subject
    chosen_files = random.sample(subject_map[subject], images_per_subject)

    for file in chosen_files:
        src_path = os.path.join(source_dir, file)
        dst_path = os.path.join(subject_folder, file)
        shutil.copy(src_path, dst_path)

print(f"\n✅ Success! Data organized in {base_output_dir}")
print(f"Total folders: {len(os.listdir(base_output_dir))}")